version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      # Optional: Add any pre-build commands, e.g., running tests

  build:
    commands:
      - echo "Building the package..."
      - zip -r9 function.zip . -x "*tests*"

artifacts:
  files:
    - function.zip
