version: 0.2

phases:
  install:
    commands:
      - echo "Upgrading pip to the latest version..."
      - pip install --upgrade pip
      - echo "Creating virtual environment..."
      - python -m venv venv
      - source venv/bin/activate
      - echo "Installing dependencies..."
      - pip install -r requirements.txt --verbose

  pre_build:
    commands:
      - echo "Running pre-build steps..."

  build:
    commands:
      - echo "Building the package..."
      - zip -r9 function.zip . -x "*tests*"

artifacts:
  files:
    - function.zip
