version: 0.2

phases:
  install:
    commands:
      - echo "Upgrading pip..."
      - pip install --upgrade pip
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .

  pre_build:
    commands:
      - echo "Running pre-build steps..."

  build:
    commands:
      - echo "Building the package..."
      - zip -r9 function.zip . -x "*tests*"

artifacts:
  files:
    - function.zip
