services:
- type: web
  name: latestdokkubot
  runtime: python
  repo: https://github.com/dokkumeme/dokkubot
  plan: free
  envVars:
  - key: PYTHON_VERSION
    sync: false
  - key: LOG_CHANNEL
    sync: false
  - key: DATABASE_URI
    sync: false
  - key: DATABASE_NAME
    sync: false
  - key: CHANNELS
    sync: false
  - key: API_HASH
    sync: false
  - key: BOT_TOKEN
    sync: false
  - key: API_ID
    sync: false
  - key: ADMINS
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app & python3 bot.py
  healthCheckPath: /health
version: "1"
