version: "1"
services:
  - type: web
    name: latestdokkubot
    env: python
    runtime: python
    repo: https://github.com/dokkumeme/dokkubot
    plan: free
    startCommand: gunicorn app:app & python3 bot.py &
    buildCommand: pip3 install -U -r requirements.txt
    region: oregon
    branch: main
    numInstances: 1
    healthCheckPath: /health
    gracefulShutdown:
      gracePeriodSeconds: 60  # Set the grace period as needed
    envVars:
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 120 --workers 4"
    autoDeploy: true
    deployment:
      strategy: rolling
